name: Check PR Formatting
on:
  pull_request:

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'corretto'

      - name: Grant exectute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck